### ISSUE TITLE
NameError: name 'ph' is not defined

### ISSUE THREAD

**Issue by karolproksa** [xjdeng/pinterest-image-scraper#19]
>>> images = ph.runme("https://www.pinterest.com.au/natalie_jane7/outdoor-portrait-photography/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ph' is not defined
>>> s.download(images)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'images' is not defined
>>> images = ph.runme("https://www.pinterest.com.au/natalie_jane7/outdoor-portrait-photography/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ph' is not defined
>>> ph = s.Pinterest_Helper("ivihhxhwmmfbsfcotl@wqcefp.online" , "my_password_here")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pinterest_scraper/scraper.py", line 58, in __init__
    emailElem = self.browser.find_element_by_name('id')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 496, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [name="id"]

**Comment by Aquahugs** [comment]
This error still exist
