### ISSUE TITLE
"The browser appears to have exited "

### ISSUE THREAD

**Issue by LoneWolfsMoon** [xjdeng/pinterest-image-scraper#4]
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aleksandar/pinterest-image-scraper/pinterest_scraper/scraper.py", line 53, in __init__
    self.browser = webdriver.Firefox(firefox_profile=profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 99, in _wait_until_connectable
    "The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

**Comment by LoneWolfsMoon** [comment]
I found the solution:
I downgraded my packages
`sudo apt-get install firefox=45.0.2+build1-0ubuntu1
`
